### PR TITLE
Version 14

### PR DESCRIPTION
**Pull request by franzeulatenextroll**

### CODE REVIEW

**Comment by guschnwg** [comment]
Check if we still need the changes in https://github.com/SemanticSugar/facebook-python-business-sdk/pull/26

**Comment by franzeulatenextroll** [comment]
@guschnwg the fix was applied

**Comment by guschnwg** [comment]
Looking good. If the functional tests are working then it is fine to be merged and shipped.

`ipython`

```
from facebook_business import FacebookSession
from facebook_business import FacebookAdsApi
from facebook_business.adobjects import adaccount

# You can get these below from cats4gold
session = FacebookSession(
    cfg.FACEBOOK_APP_ID,
    cfg.FACEBOOK_APP_SECRET,
    cfg.FACEBOOK_ACCESS_TOKEN,
)
api = FacebookAdsApi(session)

act = adaccount.AdAccount("act_1703098119930984", api=api)
cursor = act.get_ad_creatives(fields=["thumbnail_url"], params={"limit": 1, "thumbnail_width": 1000, "thumbnail_height": 1000})

c1 = next(cursor)
c2 = next(cursor)
c3 = next(cursor)

# Make sure c1, c2, and c3 all have thumbnail_urls with a good size
```

**Review by guschnwg — APPROVED** [review]

**Comment by franzeulatenextroll** [comment]
@guschnwg this is working, but I don't have the permission to merge this PR, so can you help me with that please.
image

**Pull request merged**
