### PR TITLE
resolved conflicts v2.4 of sdk

### PR DESCRIPTION
**Pull request by nilesnelson**
upgrade (by merging facebook branch) sdk so we can upgraded to v2.4 of the api

@jonowar

### CODE REVIEW

**Comment by jonowar** [comment]
ohgosh what is all this other crud?

**Comment by nilesnelson** [comment]
all the recent updates to the sdk, from the original facebook branch. since there were new fields/ other requirements now with v2.4 of the api, needed the updates to the sdk.

**Comment by jonowar** [comment]
should we modify the package version in setup.py to indicate that this is merged with official facebook master, but that we've modified it? so we can add to artifactory and such.

**Comment by nilesnelson** [comment]
i wasn't worried about that yet, figured i would just do that when i went to upload it to artifactory, i can do that in this PR tho (now that i think about it sounds like the more clear way)

**Pull request merged**
